"""add create_date default2

Revision ID: 1c474ba7428b
Revises: da460dbd2dbe
Create Date: 2026-01-09 10:05:52.795120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c474ba7428b'
down_revision: Union[str, Sequence[str], None] = 'da460dbd2dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sale_invoices_in_progress ALTER COLUMN create_date SET DEFAULT now()")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE sale_invoices_in_progress ALTER COLUMN create_date DROP DEFAULT")
    # ### end Alembic commands ###
