"""add check_payment

Revision ID: 40cc630e9332
Revises: 427d4bdfeab0
Create Date: 2026-01-08 20:21:20.285394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cc630e9332'
down_revision: Union[str, Sequence[str], None] = '427d4bdfeab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices_in_progress', sa.Column('month_count', sa.SMALLINT(), nullable=False))
    op.add_column('sale_invoices_in_progress', sa.Column('chat_id', sa.BIGINT(), nullable=False))
    op.drop_column('sale_invoices_in_progress', 'month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices_in_progress', sa.Column('month', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('sale_invoices_in_progress', 'chat_id')
    op.drop_column('sale_invoices_in_progress', 'month_count')
    # ### end Alembic commands ###
