"""add server for wh

Revision ID: 7f38eb3a6b92
Revises: b10fcf573815
Create Date: 2026-03-28 14:00:22.626640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f38eb3a6b92'
down_revision: Union[str, Sequence[str], None] = 'b10fcf573815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('is_wl', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'is_wl')
    # ### end Alembic commands ###
