"""edit invoices

Revision ID: 9d242a224f3a
Revises: d822138a6479
Create Date: 2026-03-27 18:19:37.547569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d242a224f3a'
down_revision: Union[str, Sequence[str], None] = 'd822138a6479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices_in_progress', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sale_invoices_in_progress', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices_in_progress', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sale_invoices_in_progress', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
