"""test

Revision ID: 9e26c95f32ab
Revises: bbf192760ce0
Create Date: 2025-08-11 19:33:38.601946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26c95f32ab'
down_revision: Union[str, Sequence[str], None] = 'bbf192760ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('speed', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'speed')
    # ### end Alembic commands ###
