"""add create_date

Revision ID: a2cf6f041e7e
Revises: 40cc630e9332
Create Date: 2026-01-08 20:59:28.356948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf6f041e7e'
down_revision: Union[str, Sequence[str], None] = '40cc630e9332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices_in_progress', sa.Column('create_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices_in_progress', 'create_date')
    # ### end Alembic commands ###
