"""add is_gift

Revision ID: b0d512fdc53b
Revises: 9d242a224f3a
Create Date: 2026-03-28 11:46:13.108408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d512fdc53b'
down_revision: Union[str, Sequence[str], None] = '9d242a224f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices_in_progress', sa.Column('is_gift', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices_in_progress', 'is_gift')
    # ### end Alembic commands ###
