"""add is_gift2

Revision ID: b10fcf573815
Revises: b0d512fdc53b
Create Date: 2026-03-28 11:53:48.081418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10fcf573815'
down_revision: Union[str, Sequence[str], None] = 'b0d512fdc53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices_in_progress', 'server_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices_in_progress', 'server_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
