"""test

Revision ID: bbf192760ce0
Revises: 
Create Date: 2025-08-11 18:40:04.718215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf192760ce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift_codes', 'month',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_constraint(op.f('uniqCode'), 'gift_codes', type_='unique')
    op.drop_constraint(op.f('hash_uniq'), 'securityhashs', type_='unique')
    op.drop_index(op.f('fki_а'), table_name='users_subscription')
    op.create_foreign_key(None, 'users_subscription', 'servers', ['server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_subscription', type_='foreignkey')
    op.create_index(op.f('fki_а'), 'users_subscription', ['invited'], unique=False)
    op.create_unique_constraint(op.f('hash_uniq'), 'securityhashs', ['hash'], postgresql_include=['hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uniqCode'), 'gift_codes', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('gift_codes', 'month',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
