"""add strategy server

Revision ID: cd6ffd579147
Revises: 7f38eb3a6b92
Create Date: 2026-04-13 13:24:52.708380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6ffd579147'
down_revision: Union[str, Sequence[str], None] = '7f38eb3a6b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('strategy', sa.SMALLINT(), nullable=True))
